live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin/catppuccin-mocha.yml"
]
[env]
TERM = xterm-256color
[window]
startup_mode = "Maximized"
decorations = "Full"
padding = { x = 0, y = 32 }
[font]
size = 16.0
offset = { x = 0, y = 4 }
[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Thin"
[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"
[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "LightItalic"
[[hints.enabled]]
command = "open"
hyperlinks = true
mouse.enabled = true

